### ISSUE TITLE
Avoid default packages

### ISSUE THREAD

**Issue by djdupre** [cse403trackforever/server#6]
Using default packages is bad practice and will cause problems if we use [Spring](https://docs.spring.io/spring-boot/docs/current/reference/html/using-boot-structuring-your-code.html#using-boot-using-the-default-package) later on. We should move our code into some 'trackforever' package now.

**Comment by cjteam123** [comment]
We could do com.trackforever.server as our default path

**Comment by cjteam123** [comment]
Fix is now available via PR #7

**Comment by cjteam123** [comment]
Fixed
