### ISSUE TITLE
Split structures module up into submodules

### ISSUE THREAD

**Issue by cjteam123** [cse403trackforever/server#9]
There are way too many files in the structures module and this hurts readability. They should be split up in some manner.

**Comment by WilliamCao13** [comment]
Would separating them into their own packages work?

**Comment by cjteam123** [comment]
That's definitely one possibility!
Otherwise something like
Structures ----> GoogleCode ---> *
                   |
                   | -----> GitHub --------> *
Ect
Would work

**Comment by WilliamCao13** [comment]
The real question is, am I allowed to push straight to master?

**Comment by cjteam123** [comment]
Nope.
You'll need to make a branch and then a pr
